# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DbChkDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DbChkDialog(object):
    def setupUi(self, DbChkDialog):
        DbChkDialog.setObjectName("DbChkDialog")
        DbChkDialog.resize(700, 500)
        self.chkResult = QtWidgets.QLabel(DbChkDialog)
        self.chkResult.setGeometry(QtCore.QRect(220, 280, 381, 171))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.chkResult.setFont(font)
        self.chkResult.setStyleSheet("")
        self.chkResult.setText("")
        self.chkResult.setObjectName("chkResult")
        self.oldCode = QtWidgets.QTextEdit(DbChkDialog)
        self.oldCode.setEnabled(True)
        self.oldCode.setGeometry(QtCore.QRect(80, 50, 601, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.oldCode.setFont(font)
        self.oldCode.setObjectName("oldCode")
        self.label = QtWidgets.QLabel(DbChkDialog)
        self.label.setGeometry(QtCore.QRect(30, 300, 121, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.DbErrorNum = QtWidgets.QLabel(DbChkDialog)
        self.DbErrorNum.setGeometry(QtCore.QRect(60, 330, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.DbErrorNum.setFont(font)
        self.DbErrorNum.setObjectName("DbErrorNum")
        self.newCode = QtWidgets.QTextEdit(DbChkDialog)
        self.newCode.setGeometry(QtCore.QRect(80, 170, 601, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newCode.setFont(font)
        self.newCode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newCode.setObjectName("newCode")
        self.newCodeIn = QtWidgets.QLineEdit(DbChkDialog)
        self.newCodeIn.setGeometry(QtCore.QRect(30, 10, 651, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.newCodeIn.setFont(font)
        self.newCodeIn.setObjectName("newCodeIn")
        self.label_2 = QtWidgets.QLabel(DbChkDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DbChkDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(DbChkDialog)
        QtCore.QMetaObject.connectSlotsByName(DbChkDialog)

    def retranslateUi(self, DbChkDialog):
        _translate = QtCore.QCoreApplication.translate
        DbChkDialog.setWindowTitle(_translate("DbChkDialog", "复扫核对"))
        self.label.setText(_translate("DbChkDialog", "错误次数(<=2)"))
        self.DbErrorNum.setText(_translate("DbChkDialog", "0"))
        self.label_2.setText(_translate("DbChkDialog", "原始"))
        self.label_3.setText(_translate("DbChkDialog", "复扫"))

